/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSLock, NSMutableDictionary, NSString;

@interface CPDistributedMessagingCenter : NSObject
{
    NSString *_name;
    NSLock *_lock;
    unsigned int _sendPort;
    NSString *_requiredEntitlement;
    NSMutableDictionary *_callouts;
    BOOL _isServer;
}

+ (id)centerNamed:(id)fp8;
- (id)_initWithServerName:(id)fp8;
- (void)dealloc;
- (id)name;
- (unsigned int)_sendPort;
- (BOOL)sendMessageName:(id)fp8 userInfo:(id)fp12;
- (id)sendMessageAndReceiveReplyName:(id)fp8 userInfo:(id)fp12;
- (BOOL)_sendMessage:(id)fp8 userInfo:(id)fp12 receiveReply:(id *)fp16;
- (void)runServerOnCurrentThread;
- (void)runServerOnCurrentThreadProtectedByEntitlement:(id)fp8;
- (void)registerForMessageName:(id)fp8 target:(id)fp12 selector:(SEL)fp16;
- (void)unregisterForMessageName:(id)fp8;
- (BOOL)_dispatchMessageNamed:(id)fp8 userInfo:(id)fp12 auditToken:(id *)fp16 reply:(id *)fp20;
- (BOOL)isTaskEntitled:(id *)fp8;

@end

